# Generated by Django 4.0.5 on 2022-06-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_profile_followers_alter_profile_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dweet', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
