# Generated by Django 4.0.5 on 2022-06-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_dweets_alter_profile_followers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dweets',
            new_name='Dweet',
        ),
    ]
