# Generated by Django 4.0.5 on 2022-06-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_rename_dweets_dweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweet',
            name='user_id',
            field=models.PositiveIntegerField(),
        ),
    ]
